### ISSUE TITLE
Deactivate macOS CI runners?

### ISSUE THREAD

**Issue by ahelwer** [tlaplus/Examples#119]
Currently the macOS CI takes over twice as long to run as the linux and windows CI runs: https://github.com/tlaplus/Examples/actions/runs/7835386801

This got substantially worse after the work to add models to most of the specs, because macOS CI runners see a strange amount of overhead for each model (for example a model taking 1 second to run on the other runners takes 8 seconds to run on the macOS runner). Looking online it seems slow macOS CI runners is a common problem experienced by developers across github.

Ideally the CI would run for ten minutes at most, and I don't think the macOS runner is providing enough value (given the similarity to linux) to justify keeping it around. Perhaps we could add a scheduled CI run to test on macOS once per week.

**Comment by lemmy** [comment]
AFAIK there are also much faster m1-based Github runners now.

**Comment by ahelwer** [comment]
Ah, you have to specify macos-14 instead of macos-latest to get those. Running the CI with that it does seem as though it's faster. Great, problem solved!

**Comment by lemmy** [comment]
I recommend reactivating macOS for the same reason it was kept for [tlaplus/tlaplus](https://github.com/tlaplus/tlaplus/issues/986). macOS is the most popular platform and shares similarities with Linux, though it is not identical. Additionally, the rate of changes in this repository is very low, so allowing 30 minutes instead of 15 minutes for tasks is acceptable.
