### ISSUE TITLE
Do not suppress TLC output

### ISSUE THREAD

**Issue by lemmy** [tlaplus/Examples#85]
@ahelwer Diagnosing CI failures becomes much easier when you have TLC's output included. I'm wondering, is there a particular reason why TLC's stdout/stderr is currently being suppressed?

https://github.com/tlaplus/Examples/blob/7d129a9c90bf6d4d9c3f7f3fe2db5f30f3bb6913/.github/scripts/tla_utils.py#L102C13-L102C27

**Comment by lemmy** [comment]
There is no output in https://github.com/tlaplus/tlaplus/actions/runs/5777349411/job/15657634708

**Comment by ahelwer** [comment]
Harder to see but it's due to it hitting the hard timeout of 60 seconds:
```
INFO:root:examples/specifications/CheckpointCoordination/MCCheckpointCoordinationFailure.cfg
ERROR:root:examples/specifications/CheckpointCoordination/MCCheckpointCoordinationFailure.cfg timed out
```
Which is unusual, because that particular model usually finishes within 15 seconds looking at past runs. Possibly indicative of a bug?

You're right though, we don't print TLC's stdout/stderr output in the event of hitting a hard timeout. It's possible it might not be available since that results in an exception being thrown... will do some experimentation.
